---
# Main tasks file for the PostgreSQL Swarm role

# Setup PostgreSQL packages and configuration
- name: Include setup tasks
  ansible.builtin.import_tasks: setup.yml

# Deploy PostgreSQL container in Docker Swarm
- name: Include container deployment tasks
  ansible.builtin.import_tasks: container.yml

# Create databases and users
- name: Include database management tasks
  ansible.builtin.import_tasks: database.yml

# Configure backups (pg_dump)
- name: Include backup configuration tasks
  ansible.builtin.import_tasks: backup.yml
  when: postgres_backup_enabled | bool
